### ISSUE TITLE
Database Seeds

### ISSUE THREAD

**Issue by KevKodes** [KevKodes/InstaLock#2]
Basic seed data

- [x] users
- [x] posts
- [x] comments
- [x] likes
- [x] follows

**Comment by dpxrk** [comment]
I'm working on getting the API for our seed data!

**Comment by RobertVogue** [comment]
finished seeding users and post data

**Comment by dpxrk** [comment]
Another thing is that we will not be using the api for any seed data. Will be redo-ing /discovery.
