### ISSUE TITLE
Redux Store Setup

### ISSUE THREAD

**Issue by KevKodes** [KevKodes/InstaLock#7]
- [x] Auth
- [x] Posts
- [x] Comments
- [x] Likes
- [x] Follows

**Comment by dpxrk** [comment]
I'm going to tackle this with Bo Friday night! 3.19.

**Comment by dpxrk** [comment]
Still attempting to do this 3.20. Scratched going about a sessionUser considering a lot of components had authenticated sent down as a prop.

**Comment by dpxrk** [comment]
completed the auth/Session Store!

**Comment by dpxrk** [comment]
Was able to put the logged in user into the redux store. Tomorrow, 3.23, will be looking to remove the state of the user, and start using useSelector.
